server:
  port: 8090

jwt:
  secretKey: a!m@12itha!m@12itha!m@12itha!m@12itha!m@12itha!m@12itha!m@12itha!m@12ith
  tokenPrefix: Bearer
  tokenExpirationDate: 14
  tokenHeader: Authorization
  claimsName: authorities
  authority: authority