server:
  port: 8090

jwt:
  secretKey: a!m@12itha!m@12itha!m@12itha!m@12itha!m@12itha!m@12itha!m@12itha!m@12ith
  tokenPrefix: Bearer
  tokenExpirationDate: 14
  tokenHeader: Authorization
  claimsName: authorities
  authority: authority
  
AUTHORIZATION_SERVICE: POD-6-LB-689554527.us-west-2.elb.amazonaws.com

POLICY_SERVICE: POD-6-LB-689554527.us-west-2.elb.amazonaws.com

CONSUMER_SERVICE: POD-6-LB-689554527.us-west-2.elb.amazonaws.com
